# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/contracts/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/contracts/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/contracts/auth.proto\x12\x10medimate.auth.v1\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"I\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05roles\x18\x03 \x03(\t2o\n\x0b\x41uthService\x12`\n\rValidateToken\x12&.medimate.auth.v1.ValidateTokenRequest\x1a\'.medimate.auth.v1.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.contracts.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=46
  _globals['_VALIDATETOKENREQUEST']._serialized_end=83
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=85
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=158
  _globals['_AUTHSERVICE']._serialized_start=160
  _globals['_AUTHSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
